// CSV Template definitions for employee import

export const indonesiaTemplateColumns = [
  "employee_id",
  "imip_id",
  "name",
  "gender",
  "place_of_birth",
  "date_of_birth",
  "marital_status",
  "tax_status",
  "religion",
  "nationality",
  "blood_type",
  "education",
  "ktp_no",
  "kartu_keluarga_no",
  "npwp",
  "phone_number",
  "address",
  "city",
  "spouse_name",
  "child_name_1",
  "child_name_2",
  "child_name_3",
  "emergency_contact_name",
  "emergency_contact_phone",
  "employment_status",
  "status",
  "branch",
  "branch_id",
  "company_office",
  "work_location",
  "division",
  "department",
  "section",
  "job_title",
  "grade",
  "position_grade",
  "group_job_title",
  "direct_report",
  "locality_status",
  "point_of_hire",
  "point_of_origin",
  "schedule_type",
  "travel_in",
  "travel_out",
  "first_join_date_merdeka",
  "transfer_merdeka",
  "first_join_date",
  "join_date",
  "end_contract",
  "office_email",
  "email",
  "id_card_mti",
  "bank_name",
  "account_name",
  "account_no",
  "bpjs_tk",
  "bpjs_kes",
  "status_bpjs_kes",
  "social_insurance_no_alt",
  "bpjs_kes_no_alt",
  "insurance_endorsement",
  "insurance_owlexa",
  "insurance_fpg",
  "fpg_no",
  "owlexa_no",
  "terminated_type",
  "terminated_date",
  "terminated_reason",
  "blacklist_mti",
  "blacklist_imip",
];

export const expatTemplateColumns = [
  "insurance_endorsement",
  "insurance_owlexa",
  "insurance_fpg",
  "employee_id",
  "name",
  "gender",
  "place_of_birth",
  "date_of_birth",
  "marital_status",
  "tax_status",
  "religion",
  "nationality",
  "blood_type",
  "phone_number",
  "address",
  "city",
  "point_of_hire",
  "point_of_origin",
  "education",
  "schedule_type",
  "first_join_date_merdeka",
  "first_join_date",
  "join_date",
  "employment_status",
  "end_contract",
  "branch_id",
  "branch",
  "company_office",
  "work_location",
  "division",
  "department",
  "section",
  "direct_report",
  "job_title",
  "grade",
  "position_grade",
  "group_job_title",
  "bank_name",
  "account_name",
  "account_no",
  "npwp",
  "bpjs_tk",
  "bpjs_kes",
  "status_bpjs_kes",
  "kitas_no",
  "passport_no",
  "travel_in",
  "travel_out",
  "social_insurance_no_alt",
  "bpjs_kes_no_alt",
  "terminated_date",
  "terminated_type",
  "terminated_reason",
  "office_email",
  "status",
  "fpg_no",
  "owlexa_no",
  "id_card_mti",
  "field",
  "bank_code",
  "icbc_bank_account_no",
  "name_as_passport",
  "email",
  "passport_expiry",
  "kitas_expiry",
  "imta",
  "rptka_no",
  "rptka_position",
  "kitas_address",
  "job_title_kitas",
  "icbc_username",
  "batch",
  "note",
  "paspor_checklist",
  "kitas_checklist",
  "imta_checklist",
  "rptka_checklist",
  "npwp_checklist",
  "bpjs_kes_checklist",
  "bpjs_tk_checklist",
  "bank_checklist",
];

export const indonesiaSampleData = [
  {
    employee_id: "MTI12345",
    imip_id: "IMIP77889",
    name: "Andi Saputra",
    gender: "Male",
    place_of_birth: "Jakarta",
    date_of_birth: "1990-04-12",
    marital_status: "Married",
    tax_status: "TK0",
    religion: "Islam",
    nationality: "Indonesia",
    blood_type: "O",
    education: "S1",
    ktp_no: "3174XXXXXXXX",
    kartu_keluarga_no: "3275XXXXXXXX",
    npwp: "09.123.456.7-890.000",
    phone_number: "081234567890",
    address: "Jl. Mawar No. 12",
    city: "Jakarta Barat",
    spouse_name: "Siti Aminah",
    child_name_1: "Budi",
    child_name_2: "Sari",
    child_name_3: "",
    emergency_contact_name: "Rudi",
    emergency_contact_phone: "081298765432",
    employment_status: "active",
    status: "active",
    branch: "Morowali",
    branch_id: "MTI-SITE-01",
    company_office: "Morowali Office",
    work_location: "IMIP",
    division: "ICT",
    department: "Support Services",
    section: "IT Support",
    job_title: "ICT Supervisor",
    grade: "10",
    position_grade: "Supervisor",
    group_job_title: "System Analyst",
    direct_report: "Adi Wijaya",
    locality_status: "Local",
    travel_in: "",
    travel_out: "",
    point_of_hire: "Jakarta",
    point_of_origin: "Surabaya",
    schedule_type: "Shift",
    first_join_date_merdeka: "2020-01-15",
    transfer_merdeka: "",
    first_join_date: "2020-01-15",
    join_date: "2020-02-01",
    end_contract: "",
    office_email: "",
    email: "",
    id_card_mti: "",
    bank_name: "BRI",
    account_name: "Andi Saputra",
    account_no: "1234567890",
    bpjs_tk: "12345678901",
    bpjs_kes: "98765432100",
    status_bpjs_kes: "Active",
    social_insurance_no_alt: "",
    bpjs_kes_no_alt: "",
    insurance_endorsement: "0",
    insurance_owlexa: "1",
    insurance_fpg: "0",
    fpg_no: "",
    owlexa_no: "",
    blacklist_mti: "",
    blacklist_imip: "",
  },
];

export const expatSampleData = [
  {
    employee_id: "MTI22001",
    name: "Zhang Wei",
    gender: "Male",
    place_of_birth: "Beijing",
    date_of_birth: "1985-03-15",
    marital_status: "Married",
    tax_status: "K1",
    religion: "Buddha",
    nationality: "China",
    blood_type: "B",
    education: "S2",
    field: "Metallurgy Engineering",
    ktp_no: "",
    npwp: "09.234.567.8-901.000",
    phone_number: "+86123456789",
    email: "zhang.wei@gmail.com",
    address: "Jl. Mawar No. 7",
    city: "Morowali",
    employment_status: "contract",
    status: "active",
    company_office: "Morowali Office",
    work_location: "IMIP",
    division: "Engineering",
    department: "Production",
    section: "Mechanical",
    job_title: "Senior Engineer",
    grade: "12",
    position_grade: "Manager",
    group_job_title: "Engineering Manager",
    direct_report: "Li Ming",
    point_of_hire: "Beijing",
    schedule_type: "Roster 6:2",
    first_join_date: "2022-03-01",
    join_date: "2022-03-15",
    end_contract: "2025-03-14",
    bank_code: "002",
    icbc_bank_account_no: "ICBC998877",
    icbc_username: "zhang.icbc",
    bpjs_tk: "22345678901",
    bpjs_kes: "88765432100",
    status_bpjs_kes: "Active",
    insurance_endorsement: "1",
    insurance_owlexa: "1",
    insurance_fpg: "1",
    passport_no: "A1234567",
    name_as_passport: "ZHANG WEI",
    passport_expiry: "2030-10-10",
    kitas_no: "KITAS8899",
    kitas_expiry: "2026-01-01",
    kitas_address: "Jl. Mawar No. 7",
    job_title_kitas: "Engineer",
    imta: "IMTA778899",
    rptka_no: "RPTKA556677",
    rptka_position: "Foreign Expert",
    point_of_origin: "Beijing",
    first_join_date_merdeka: "2022-02-15",
    branch_id: "MTI-SITE-01",
    branch: "Morowali",
    bank_name: "ICBC",
    account_name: "Zhang Wei",
    account_no: "9988776655",
    travel_in: "2022-02-25",
    travel_out: "2022-04-01",
    social_insurance_no_alt: "ALT-INS-9999",
    bpjs_kes_no_alt: "ALT-KES-9999",
    terminated_date: "",
    terminated_type: "",
    terminated_reason: "",
    office_email: "zhang.wei@merdekabattery.com",
    fpg_no: "FPG-12345",
    owlexa_no: "OWL-98765",
    id_card_mti: "1",
    batch: "Batch A",
    note: "Initial import",
    paspor_checklist: "1",
    kitas_checklist: "1",
    imta_checklist: "1",
    rptka_checklist: "1",
    npwp_checklist: "1",
    bpjs_kes_checklist: "1",
    bpjs_tk_checklist: "1",
    bank_checklist: "1",
  },
];

export function generateCSV(columns: string[], data: Record<string, string>[]): string {
  const header = columns.join(",");
  const rows = data.map((row) =>
    columns.map((col) => {
      const value = row[col] || "";
      // Escape quotes and wrap in quotes if contains comma
      if (value.includes(",") || value.includes('"')) {
        return `"${value.replace(/"/g, '""')}"`;
      }
      return value;
    }).join(",")
  );
  return [header, ...rows].join("\n");
}

export function downloadCSV(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
